export default interface IDevice {
    belongs_to__application,
    build_log?,
    commit: string,
    // composition,
    created_at: string,
    end_timestamp: string,
    id: number,
    // invalidation_reason?,
    is_final: boolean,
    is_finalized_at__date?: string,
    is_invalidated: boolean,
    is_passing_tests: boolean,
    // known_issue_list?,
    // note?,
    release_type: string,
    // release_version?,
    // revision: number,
    semver?: string,
    semver_major?: number,
    semver_minor?: number,
    semver_patch?: number,
    source: string,
    start_timestamp: string,
    status: string,
    update_timestamp: string,
}